from django.urls import path

from HostelApp import views

urlpatterns=[
    path('',views.index,name='index'),
    path('signin',views.signin,name='signin'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('teacher_register',views.teacher_register,name='teacher_register'),
    path('teacher_view',views.teacher_view,name='teacher_view'),
    path('teacher_update/<int:id>',views.teacher_update,name='teacher_update'),
    path('teacher_delete/<int:id>',views.teacher_delete,name='teacher_delete'),
    path('logout',views.logout,name='logout'),
    path('student_register',views.student_register,name='student_register'),
    path('student_view',views.student_view,name='student_view'),
    path('student_update/<int:id>',views.student_update,name='student_update'),
    path('student_delete/<int:id>',views.student_delete,name='student_delete'),
    path('Room_View',views.Room_View,name='Room_View'),
    path('Room_Add',views.Room_Add,name='Room_Add'),
    path('Room_Update/<int:id>',views.Room_Update,name='Room_Update'),
    path('Room_Delete/<int:id>',views.Room_Delete,name='Room_Delete'),
    path('student_home',views.student_home,name='student_home'),
    path('Food_View',views.Food_View,name='Food_View'),
    path('Food_Add',views.Food_Add,name='Food_Add'),
    path('Food_Update/<int:id>',views.Food_Update,name='Food_Update'),
    path('Food_Delete/<int:id>',views.Food_Delete,name='Food_Delete'),
    path('stdroom_View',views.stdroom_View,name='stdroom_View'),
    path('stdfood_View',views.stdfood_View,name='stdfood_View'),
    path('teacher_home',views.teacher_home,name='teacher_home'),
    path('teacherroom_View',views.teacherroom_View,name='teacherroom_View'),
    path('teacherfood_View',views.teacherfood_View,name='teacherfood_View'),
    path('studentprofile',views.studentprofile,name='studentprofile'),
    path('add_attendance',views.add_attendance,name='add_attendance'),
    path('mark_attendance/<int:id>',views.mark_attendance,name='mark_attendance'),
    path('view_attendance/',views.view_attendance,name='view_attendance'),
    path('day_attendance/<date>',views.day_attendance,name='day_attendance'),
    path('teacherprofile',views.teacherprofile,name='teacherprofile'),
    path('std_viewAtt',views.std_viewAtt,name='std_viewAtt'),
    path('att_view',views.att_view,name='att_view'),
    path('book_room',views.book_room,name='book_room'),
    path('booking_status/<int:id>',views.booking_status,name='booking_status'),
    path('cancel_booking/<int:id>',views.cancel_booking,name='cancel_booking'),
    path('bookings',views.bookings,name='bookings'),
    path('confirm_booking/<int:id>',views.confirm_booking,name='confirm_booking'),
    path('reject_booking/<int:id>',views.reject_booking,name='reject_booking'),
    path('complaintAdd',views.complaintAdd,name='complaintAdd'),
    path('Complaint_View',views.ComplaintView,name='ComplaintView'),
    path('admincmpView',views.admincmpView,name='admincmpView'),
    path('cmpReply/<int:id>',views.cmpReply,name='cmpReply'),
    path('cmpreplyView',views.cmpreplyView,name='cmpreplyView'),
    path('bill_add',views.bill_add,name='bill_add'),
    path('bill_view',views.bill_view,name='bill_view'),
    path('bill_student_view',views.bill_student_view,name='bill_student_view'),


]